package com.travessia.segura.config

import android.content.Context

/**
 * Gerenciador simples de idioma do app.
 * Mantém todos os textos visíveis e falas em PT/EN/ES sem alterar a lógica da IA.
 */
object LanguageManager {
    const val PT = "pt"
    const val EN = "en"
    const val ES = "es"

    private const val PREFS_NAME = "travessia_config"
    private const val KEY_LANGUAGE = "app_language"

    data class LanguageOption(val code: String, val label: String)

    val options = listOf(
        LanguageOption(PT, "Português"),
        LanguageOption(EN, "English"),
        LanguageOption(ES, "Español")
    )

    fun currentLanguage(context: Context): String {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getString(KEY_LANGUAGE, PT) ?: PT
    }

    fun setLanguage(context: Context, code: String) {
        val safeCode = if (code in options.map { it.code }) code else PT
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .edit()
            .putString(KEY_LANGUAGE, safeCode)
            .apply()
    }

    fun text(context: Context, key: String): String = text(currentLanguage(context), key)

    fun text(code: String, key: String): String {
        val lang = translations[code] ?: translations[PT].orEmpty()
        return lang[key] ?: translations[PT]?.get(key) ?: key
    }

    private val translations: Map<String, Map<String, String>> = mapOf(
        PT to mapOf(
            "app_name" to "SenseWalk",
            "login_title" to "SenseWalk",
            "login_subtitle" to "Assistente visual para análise de tráfego e travessia segura.",
            "login_language_label" to "Escolha o idioma",
            "login_hint" to "Depois você poderá alterar isso em Configurações.",
            "login_continue" to "Entrar no app",
            "login_pt" to "Português",
            "login_en" to "English",
            "login_es" to "Español",

            "screen_title" to "Análise de Tráfego",
            "waiting_camera" to "Aguardando conexão com a câmera",
            "loading_model" to "Carregando modelo...",
            "ready_wifi" to "Pronto! Conecte no WiFi 'ESP-CAM-VIEW'",
            "model_error" to "ERRO ao carregar modelo!",
            "stop_before_source" to "Pare a análise antes de mudar a fonte",
            "esp_connect_info" to "Conecte-se à rede WiFi 'ESP-CAM-VIEW'\nSenha: 12345678\nIP: 192.168.4.1",
            "esp_connected" to "ESP32 conectado! Recebendo frames...",
            "esp_connection_failed" to "Não foi possível conectar ao ESP32.\nVerifique se está na rede 'ESP-CAM-VIEW'",
            "esp_connection_error" to "Erro de conexão com o ESP32.",
            "esp_no_signal" to "Sem conexão com ESP32",
            "esp_waiting" to "Aguardando sinal do ESP32",
            "esp_error_suffix" to "Verifique a conexão WiFi",
            "analysis_start_voice" to "Iniciando análise. Analisando a via...",
            "analysis_stop_voice" to "Análise encerrada.",
            "analysis_running" to "Análise em andamento",
            "analysis_paused" to "Análise pausada",
            "analyzing" to "Analisando...",
            "paused" to "Pausado.",
            "start" to "Iniciar",
            "stop" to "Parar",
            "source_local" to "Local",
            "config_short" to "Config.",
            "vehicles" to "Veículos",
            "traffic_light" to "Semáforo",
            "current_situation" to "Situação atual",
            "camera_permission_needed" to "Permissão de câmera necessária!",
            "no_camera_permission" to "Sem permissão de câmera.",
            "camera_error" to "Erro na câmera",
            "state_inactive" to "INATIVO",
            "state_recognizing" to "RECONHECENDO",
            "state_traffic_light" to "SEMÁFORO",
            "state_crosswalk" to "FAIXA",
            "state_clear_road" to "VIA LIVRE",
            "situation_safe" to "SEGURO",
            "situation_wait" to "AGUARDE",
            "situation_checking" to "VERIFICANDO",
            "color_red" to "vermelho",
            "color_green" to "verde",
            "color_yellow" to "amarelo",
            "color_unknown" to "desconhecido",
            "color_none" to "nenhum",
            "object_crosswalk" to "Faixa",
            "object_vehicle" to "veículo",
            "vehicle_car" to "carro",
            "vehicle_motorcycle" to "moto",
            "vehicle_bicycle" to "bicicleta",
            "vehicle_truck" to "caminhão",
            "vehicle_ambulance" to "ambulância",
            "motion_stopped_short" to "P",
            "motion_moving_short" to "M",
            "motion_approaching_short" to "A",

            "voice_recon_traffic_light" to "Semáforo detectado.",
            "voice_recon_crosswalk" to "Faixa de pedestre detectada.",
            "voice_recon_road" to "Monitorando a via.",
            "voice_green_light" to "Semáforo verde!",
            "voice_red_light_stop" to "Semáforo vermelho. Pare.",
            "voice_red_light_wait" to "Semáforo vermelho. Aguarde.",
            "voice_light_lost_crosswalk" to "Semáforo fora de visão. Monitorando faixa.",
            "voice_light_lost_road" to "Semáforo fora de visão. Monitorando via.",
            "voice_looking_for_light" to "Procurando semáforo.",
            "voice_green_road_clear" to "Semáforo verde. Via livre. Pode atravessar.",
            "voice_green_has_vehicles" to "Semáforo verde, mas há veículos. Aguarde.",
            "voice_green_vehicles_stopped" to "Semáforo verde. Veículos parados. Pode atravessar.",
            "voice_green_vehicles_stopping" to "Semáforo verde. Veículos parando.",
            "voice_turn_left_strong" to "Vire bastante para a esquerda.",
            "voice_turn_left_light" to "Vire levemente para a esquerda.",
            "voice_turn_right_strong" to "Vire bastante para a direita.",
            "voice_turn_right_light" to "Vire levemente para a direita.",
            "voice_aligned_crosswalk" to "Alinhado com a faixa.",
            "voice_crosswalk_clear" to "Faixa livre. Pode atravessar.",
            "voice_crosswalk_wait" to "Veículos na faixa. Aguarde.",
            "voice_vehicles_stopping" to "Veículos parando.",
            "voice_crosswalk_vehicles_stopped" to "Veículos parados. Pode atravessar pela faixa.",
            "voice_monitor_crosswalk" to "Monitorando faixa.",
            "voice_monitor_crosswalk_moving" to "Monitorando faixa. %d veículos em movimento.",
            "voice_road_clear" to "Via livre. Pode atravessar.",
            "voice_road_wait" to "Veículos na via. Aguarde.",
            "voice_road_vehicles_stopped" to "Veículos parados. Pode atravessar.",
            "voice_monitor_road" to "Monitorando via.",
            "voice_monitor_road_moving" to "Monitorando via. %d veículos em movimento.",

            "settings_title" to "Configurações",
            "settings_subtitle" to "Personalize a aparência e os parâmetros da análise de tráfego.",
            "settings_language_section" to "IDIOMA",
            "settings_language_subtitle" to "Mude o idioma das telas, textos e falas do aplicativo.",
            "settings_language" to "Idioma do app",
            "settings_language_saved" to "Idioma atualizado",
            "settings_appearance_section" to "APARÊNCIA DO APP",
            "settings_appearance_subtitle" to "Essas opções mudam só a tela, sem alterar a lógica da IA.",
            "settings_esp_fullscreen" to "Câmera ESP32 em tela cheia",
            "settings_esp_rotation" to "Rotação visual da câmera ESP32",
            "settings_show_boxes" to "Mostrar caixas de detecção",
            "settings_show_top_panel" to "Mostrar painel superior",
            "settings_show_bottom_panel" to "Mostrar painel inferior",
            "settings_ai_section" to "IA / DETECÇÃO",
            "settings_ai_subtitle" to "Ajustes já existentes do modelo e filtros.",
            "settings_confidence" to "Confiança mínima",
            "settings_inference_size" to "Tamanho da inferência",
            "settings_history" to "Histórico máximo",
            "settings_traffic_section" to "ANÁLISE DE TRÁFEGO",
            "settings_traffic_subtitle" to "Parâmetros usados na leitura da via.",
            "settings_stopped_speed" to "Velocidade parado",
            "settings_approaching_speed" to "Velocidade aproximando",
            "settings_proximity" to "Limiar de proximidade",
            "settings_time_section" to "TEMPOS E DECISÃO",
            "settings_time_subtitle" to "Controla o tempo necessário para confirmar a situação.",
            "settings_recognition_time" to "Tempo reconhecimento",
            "settings_safe_stop_time" to "Tempo parado seguro",
            "settings_recon_threshold" to "Recon threshold",
            "settings_recon_early_threshold" to "Recon early threshold",
            "settings_recon_early_min_frames" to "Recon early min frames",
            "settings_upgrade_frames" to "Upgrade frames",
            "settings_roi_section" to "REGIÃO DE INTERESSE",
            "settings_roi_subtitle" to "Use para limitar a área analisada na imagem.",
            "settings_roi_active" to "ROI ativo",
            "settings_roi_top" to "ROI topo",
            "settings_roi_bottom" to "ROI base",
            "settings_roi_left" to "ROI esquerda",
            "settings_roi_right" to "ROI direita",
            "settings_smoothing_section" to "SUAVIZAÇÃO E VOZ",
            "settings_smoothing_subtitle" to "Ajustes finais de estabilidade e resposta sonora.",
            "settings_ema" to "EMA alpha",
            "settings_min_objects" to "Mínimo de objetos",
            "settings_crosswalk_margin" to "Margem alinhamento faixa",
            "settings_heartbeat" to "Intervalo heartbeat",
            "settings_voice_volume" to "Volume da voz",
            "settings_reset" to "Restaurar padrão",
            "settings_reset_done" to "Configurações restauradas"
        ),
        EN to mapOf(
            "app_name" to "SenseWalk",
            "login_title" to "SenseWalk",
            "login_subtitle" to "Visual assistant for traffic analysis and safer crossing.",
            "login_language_label" to "Choose your language",
            "login_hint" to "You can change this later in Settings.",
            "login_continue" to "Enter app",
            "login_pt" to "Português",
            "login_en" to "English",
            "login_es" to "Español",

            "screen_title" to "Traffic Analysis",
            "waiting_camera" to "Waiting for camera connection",
            "loading_model" to "Loading model...",
            "ready_wifi" to "Ready! Connect to WiFi 'ESP-CAM-VIEW'",
            "model_error" to "ERROR loading model!",
            "stop_before_source" to "Stop the analysis before changing the source",
            "esp_connect_info" to "Connect to WiFi network 'ESP-CAM-VIEW'\nPassword: 12345678\nIP: 192.168.4.1",
            "esp_connected" to "ESP32 connected! Receiving frames...",
            "esp_connection_failed" to "Could not connect to ESP32.\nCheck if you are on the 'ESP-CAM-VIEW' network",
            "esp_connection_error" to "ESP32 connection error.",
            "esp_no_signal" to "No ESP32 connection",
            "esp_waiting" to "Waiting for ESP32 signal",
            "esp_error_suffix" to "Check the WiFi connection",
            "analysis_start_voice" to "Starting analysis. Analyzing the road...",
            "analysis_stop_voice" to "Analysis stopped.",
            "analysis_running" to "Analysis running",
            "analysis_paused" to "Analysis paused",
            "analyzing" to "Analyzing...",
            "paused" to "Paused.",
            "start" to "Start",
            "stop" to "Stop",
            "source_local" to "Local",
            "config_short" to "Settings",
            "vehicles" to "Vehicles",
            "traffic_light" to "Traffic light",
            "current_situation" to "Current situation",
            "camera_permission_needed" to "Camera permission is required!",
            "no_camera_permission" to "No camera permission.",
            "camera_error" to "Camera error",
            "state_inactive" to "INACTIVE",
            "state_recognizing" to "RECOGNIZING",
            "state_traffic_light" to "TRAFFIC LIGHT",
            "state_crosswalk" to "CROSSWALK",
            "state_clear_road" to "CLEAR ROAD",
            "situation_safe" to "SAFE",
            "situation_wait" to "WAIT",
            "situation_checking" to "CHECKING",
            "color_red" to "red",
            "color_green" to "green",
            "color_yellow" to "yellow",
            "color_unknown" to "unknown",
            "color_none" to "none",
            "object_crosswalk" to "Crosswalk",
            "object_vehicle" to "vehicle",
            "vehicle_car" to "car",
            "vehicle_motorcycle" to "motorcycle",
            "vehicle_bicycle" to "bicycle",
            "vehicle_truck" to "truck",
            "vehicle_ambulance" to "ambulance",
            "motion_stopped_short" to "S",
            "motion_moving_short" to "M",
            "motion_approaching_short" to "A",

            "voice_recon_traffic_light" to "Traffic light detected.",
            "voice_recon_crosswalk" to "Crosswalk detected.",
            "voice_recon_road" to "Monitoring the road.",
            "voice_green_light" to "Green light!",
            "voice_red_light_stop" to "Red light. Stop.",
            "voice_red_light_wait" to "Red light. Wait.",
            "voice_light_lost_crosswalk" to "Traffic light is out of view. Monitoring the crosswalk.",
            "voice_light_lost_road" to "Traffic light is out of view. Monitoring the road.",
            "voice_looking_for_light" to "Looking for the traffic light.",
            "voice_green_road_clear" to "Green light. Road clear. You may cross.",
            "voice_green_has_vehicles" to "Green light, but there are vehicles. Wait.",
            "voice_green_vehicles_stopped" to "Green light. Vehicles stopped. You may cross.",
            "voice_green_vehicles_stopping" to "Green light. Vehicles are stopping.",
            "voice_turn_left_strong" to "Turn far to the left.",
            "voice_turn_left_light" to "Turn slightly to the left.",
            "voice_turn_right_strong" to "Turn far to the right.",
            "voice_turn_right_light" to "Turn slightly to the right.",
            "voice_aligned_crosswalk" to "Aligned with the crosswalk.",
            "voice_crosswalk_clear" to "Crosswalk clear. You may cross.",
            "voice_crosswalk_wait" to "Vehicles on the crosswalk. Wait.",
            "voice_vehicles_stopping" to "Vehicles are stopping.",
            "voice_crosswalk_vehicles_stopped" to "Vehicles stopped. You may cross at the crosswalk.",
            "voice_monitor_crosswalk" to "Monitoring the crosswalk.",
            "voice_monitor_crosswalk_moving" to "Monitoring the crosswalk. %d vehicles moving.",
            "voice_road_clear" to "Road clear. You may cross.",
            "voice_road_wait" to "Vehicles on the road. Wait.",
            "voice_road_vehicles_stopped" to "Vehicles stopped. You may cross.",
            "voice_monitor_road" to "Monitoring the road.",
            "voice_monitor_road_moving" to "Monitoring the road. %d vehicles moving.",

            "settings_title" to "Settings",
            "settings_subtitle" to "Customize the interface and traffic analysis parameters.",
            "settings_language_section" to "LANGUAGE",
            "settings_language_subtitle" to "Change the language used in screens, texts and voice alerts.",
            "settings_language" to "App language",
            "settings_language_saved" to "Language updated",
            "settings_appearance_section" to "APP APPEARANCE",
            "settings_appearance_subtitle" to "These options only change the interface without changing the AI logic.",
            "settings_esp_fullscreen" to "ESP32 camera fullscreen",
            "settings_esp_rotation" to "ESP32 camera visual rotation",
            "settings_show_boxes" to "Show detection boxes",
            "settings_show_top_panel" to "Show top panel",
            "settings_show_bottom_panel" to "Show bottom panel",
            "settings_ai_section" to "AI / DETECTION",
            "settings_ai_subtitle" to "Existing model and filter settings.",
            "settings_confidence" to "Minimum confidence",
            "settings_inference_size" to "Inference size",
            "settings_history" to "Maximum history",
            "settings_traffic_section" to "TRAFFIC ANALYSIS",
            "settings_traffic_subtitle" to "Parameters used to read the road.",
            "settings_stopped_speed" to "Stopped speed",
            "settings_approaching_speed" to "Approaching speed",
            "settings_proximity" to "Proximity threshold",
            "settings_time_section" to "TIME AND DECISION",
            "settings_time_subtitle" to "Controls the time needed to confirm the situation.",
            "settings_recognition_time" to "Recognition time",
            "settings_safe_stop_time" to "Safe stop time",
            "settings_recon_threshold" to "Recognition threshold",
            "settings_recon_early_threshold" to "Early recognition threshold",
            "settings_recon_early_min_frames" to "Early recognition minimum frames",
            "settings_upgrade_frames" to "Upgrade frames",
            "settings_roi_section" to "REGION OF INTEREST",
            "settings_roi_subtitle" to "Use this to limit the analyzed area in the image.",
            "settings_roi_active" to "ROI active",
            "settings_roi_top" to "ROI top",
            "settings_roi_bottom" to "ROI bottom",
            "settings_roi_left" to "ROI left",
            "settings_roi_right" to "ROI right",
            "settings_smoothing_section" to "SMOOTHING AND VOICE",
            "settings_smoothing_subtitle" to "Final stability and voice response settings.",
            "settings_ema" to "EMA alpha",
            "settings_min_objects" to "Minimum objects",
            "settings_crosswalk_margin" to "Crosswalk alignment margin",
            "settings_heartbeat" to "Heartbeat interval",
            "settings_voice_volume" to "Voice volume",
            "settings_reset" to "Restore defaults",
            "settings_reset_done" to "Settings restored"
        ),
        ES to mapOf(
            "app_name" to "SenseWalk",
            "login_title" to "SenseWalk",
            "login_subtitle" to "Asistente visual para análisis de tráfico y cruce seguro.",
            "login_language_label" to "Elige el idioma",
            "login_hint" to "Después podrás cambiar esto en Configuración.",
            "login_continue" to "Entrar en la app",
            "login_pt" to "Português",
            "login_en" to "English",
            "login_es" to "Español",

            "screen_title" to "Análisis de Tráfico",
            "waiting_camera" to "Esperando conexión con la cámara",
            "loading_model" to "Cargando modelo...",
            "ready_wifi" to "Listo. Conéctate al WiFi 'ESP-CAM-VIEW'",
            "model_error" to "ERROR al cargar el modelo!",
            "stop_before_source" to "Detén el análisis antes de cambiar la fuente",
            "esp_connect_info" to "Conéctate a la red WiFi 'ESP-CAM-VIEW'\nContraseña: 12345678\nIP: 192.168.4.1",
            "esp_connected" to "ESP32 conectado. Recibiendo frames...",
            "esp_connection_failed" to "No fue posible conectar al ESP32.\nVerifica si estás en la red 'ESP-CAM-VIEW'",
            "esp_connection_error" to "Error de conexión con el ESP32.",
            "esp_no_signal" to "Sin conexión con ESP32",
            "esp_waiting" to "Esperando señal del ESP32",
            "esp_error_suffix" to "Verifica la conexión WiFi",
            "analysis_start_voice" to "Iniciando análisis. Analizando la vía...",
            "analysis_stop_voice" to "Análisis finalizado.",
            "analysis_running" to "Análisis en curso",
            "analysis_paused" to "Análisis pausado",
            "analyzing" to "Analizando...",
            "paused" to "Pausado.",
            "start" to "Iniciar",
            "stop" to "Detener",
            "source_local" to "Local",
            "config_short" to "Config.",
            "vehicles" to "Vehículos",
            "traffic_light" to "Semáforo",
            "current_situation" to "Situación actual",
            "camera_permission_needed" to "Se requiere permiso de cámara!",
            "no_camera_permission" to "Sin permiso de cámara.",
            "camera_error" to "Error de cámara",
            "state_inactive" to "INACTIVO",
            "state_recognizing" to "RECONOCIENDO",
            "state_traffic_light" to "SEMÁFORO",
            "state_crosswalk" to "CRUCE",
            "state_clear_road" to "VÍA LIBRE",
            "situation_safe" to "SEGURO",
            "situation_wait" to "ESPERA",
            "situation_checking" to "VERIFICANDO",
            "color_red" to "rojo",
            "color_green" to "verde",
            "color_yellow" to "amarillo",
            "color_unknown" to "desconocido",
            "color_none" to "ninguno",
            "object_crosswalk" to "Cruce",
            "object_vehicle" to "vehículo",
            "vehicle_car" to "auto",
            "vehicle_motorcycle" to "moto",
            "vehicle_bicycle" to "bicicleta",
            "vehicle_truck" to "camión",
            "vehicle_ambulance" to "ambulancia",
            "motion_stopped_short" to "D",
            "motion_moving_short" to "M",
            "motion_approaching_short" to "A",

            "voice_recon_traffic_light" to "Semáforo detectado.",
            "voice_recon_crosswalk" to "Cruce peatonal detectado.",
            "voice_recon_road" to "Monitoreando la vía.",
            "voice_green_light" to "Semáforo verde!",
            "voice_red_light_stop" to "Semáforo rojo. Detente.",
            "voice_red_light_wait" to "Semáforo rojo. Espera.",
            "voice_light_lost_crosswalk" to "Semáforo fuera de visión. Monitoreando el cruce.",
            "voice_light_lost_road" to "Semáforo fuera de visión. Monitoreando la vía.",
            "voice_looking_for_light" to "Buscando semáforo.",
            "voice_green_road_clear" to "Semáforo verde. Vía libre. Puedes cruzar.",
            "voice_green_has_vehicles" to "Semáforo verde, pero hay vehículos. Espera.",
            "voice_green_vehicles_stopped" to "Semáforo verde. Vehículos detenidos. Puedes cruzar.",
            "voice_green_vehicles_stopping" to "Semáforo verde. Vehículos deteniéndose.",
            "voice_turn_left_strong" to "Gira bastante hacia la izquierda.",
            "voice_turn_left_light" to "Gira levemente hacia la izquierda.",
            "voice_turn_right_strong" to "Gira bastante hacia la derecha.",
            "voice_turn_right_light" to "Gira levemente hacia la derecha.",
            "voice_aligned_crosswalk" to "Alineado con el cruce.",
            "voice_crosswalk_clear" to "Cruce libre. Puedes cruzar.",
            "voice_crosswalk_wait" to "Vehículos en el cruce. Espera.",
            "voice_vehicles_stopping" to "Vehículos deteniéndose.",
            "voice_crosswalk_vehicles_stopped" to "Vehículos detenidos. Puedes cruzar por el cruce.",
            "voice_monitor_crosswalk" to "Monitoreando el cruce.",
            "voice_monitor_crosswalk_moving" to "Monitoreando el cruce. %d vehículos en movimiento.",
            "voice_road_clear" to "Vía libre. Puedes cruzar.",
            "voice_road_wait" to "Vehículos en la vía. Espera.",
            "voice_road_vehicles_stopped" to "Vehículos detenidos. Puedes cruzar.",
            "voice_monitor_road" to "Monitoreando la vía.",
            "voice_monitor_road_moving" to "Monitoreando la vía. %d vehículos en movimiento.",

            "settings_title" to "Configuración",
            "settings_subtitle" to "Personaliza la apariencia y los parámetros del análisis de tráfico.",
            "settings_language_section" to "IDIOMA",
            "settings_language_subtitle" to "Cambia el idioma de pantallas, textos y alertas de voz.",
            "settings_language" to "Idioma de la app",
            "settings_language_saved" to "Idioma actualizado",
            "settings_appearance_section" to "APARIENCIA DE LA APP",
            "settings_appearance_subtitle" to "Estas opciones solo cambian la pantalla, sin cambiar la lógica de la IA.",
            "settings_esp_fullscreen" to "Cámara ESP32 en pantalla completa",
            "settings_esp_rotation" to "Rotación visual de la cámara ESP32",
            "settings_show_boxes" to "Mostrar cajas de detección",
            "settings_show_top_panel" to "Mostrar panel superior",
            "settings_show_bottom_panel" to "Mostrar panel inferior",
            "settings_ai_section" to "IA / DETECCIÓN",
            "settings_ai_subtitle" to "Ajustes existentes del modelo y filtros.",
            "settings_confidence" to "Confianza mínima",
            "settings_inference_size" to "Tamaño de inferencia",
            "settings_history" to "Historial máximo",
            "settings_traffic_section" to "ANÁLISIS DE TRÁFICO",
            "settings_traffic_subtitle" to "Parámetros usados en la lectura de la vía.",
            "settings_stopped_speed" to "Velocidad detenido",
            "settings_approaching_speed" to "Velocidad acercándose",
            "settings_proximity" to "Límite de proximidad",
            "settings_time_section" to "TIEMPOS Y DECISIÓN",
            "settings_time_subtitle" to "Controla el tiempo necesario para confirmar la situación.",
            "settings_recognition_time" to "Tiempo de reconocimiento",
            "settings_safe_stop_time" to "Tiempo seguro detenido",
            "settings_recon_threshold" to "Umbral de reconocimiento",
            "settings_recon_early_threshold" to "Umbral de reconocimiento temprano",
            "settings_recon_early_min_frames" to "Frames mínimos reconocimiento temprano",
            "settings_upgrade_frames" to "Frames de actualización",
            "settings_roi_section" to "REGIÓN DE INTERÉS",
            "settings_roi_subtitle" to "Usa esto para limitar el área analizada en la imagen.",
            "settings_roi_active" to "ROI activo",
            "settings_roi_top" to "ROI superior",
            "settings_roi_bottom" to "ROI inferior",
            "settings_roi_left" to "ROI izquierda",
            "settings_roi_right" to "ROI derecha",
            "settings_smoothing_section" to "SUAVIZACIÓN Y VOZ",
            "settings_smoothing_subtitle" to "Ajustes finales de estabilidad y respuesta por voz.",
            "settings_ema" to "EMA alpha",
            "settings_min_objects" to "Mínimo de objetos",
            "settings_crosswalk_margin" to "Margen de alineación del cruce",
            "settings_heartbeat" to "Intervalo heartbeat",
            "settings_voice_volume" to "Volumen de voz",
            "settings_reset" to "Restaurar valores",
            "settings_reset_done" to "Configuración restaurada"
        )
    )
}
